// <auto-generated />
using System;
using ICS.Project.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ICS.Project.DAL.Migrations
{
    [DbContext(typeof(MessengerDbContext))]
    [Migration("20190429095811_add more seed data")]
    partial class addmoreseeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ICS.Project.DAL.Entities.CommentEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AuthorId");

                    b.Property<string>("MessageText");

                    b.Property<Guid?>("PostId");

                    b.Property<DateTime>("PublishDate");

                    b.HasKey("ID");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            ID = new Guid("ec16e27a-07e2-0f47-b09d-0f362003ca83"),
                            AuthorId = new Guid("ec16e27a-47e2-4f47-b19d-1a362003ca83"),
                            MessageText = "Pro eu tation saperet, et sea brute similique theophrastus. Nec ex verear facilisi conceptam, novum postulant definitiones mei at.",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-07e2-0f47-b19d-0f362003ca83"),
                            AuthorId = new Guid("ec16e27a-47e2-4f47-b19d-2a362003ca83"),
                            MessageText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-07e2-0f47-b29d-0f362003ca83"),
                            AuthorId = new Guid("ec16e27a-47e2-4f47-b19d-0a362003ca83"),
                            MessageText = "Partem scripta laoreet ei cum. Ea vel dico vocibus omittam, pro mollis tamquam efficiendi an.",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-07e2-0f47-b39d-0f362003ca83"),
                            AuthorId = new Guid("ec16e27a-47e2-4f47-b19d-3a362003ca83"),
                            MessageText = "Mel at viris fuisset, vis diceret meliore ut.",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-07e2-4f47-b49d-0f362003ca83"),
                            AuthorId = new Guid("ec16e27a-47e2-4f47-b19d-3a362003ca83"),
                            MessageText = "Nec iudico soluta vocent id, qui ferri perfecto te. Quo id tota dicam volumus.",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-07e2-4f47-b59d-0f362003ca83"),
                            AuthorId = new Guid("ec16e27a-47e2-4f47-b19d-2a362003ca83"),
                            MessageText = "Quo clita quaeque id, ei vel invenire persecuti.",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-07e2-1f47-b69d-0f362003ca83"),
                            AuthorId = new Guid("ec16e27a-47e2-4f47-b19d-2a362003ca83"),
                            MessageText = "o exerci nonumes has, sit in sumo assum dissentias.",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-07e2-1f47-b79d-0f362003ca83"),
                            AuthorId = new Guid("ec16e27a-47e2-4f47-b19d-1a362003ca83"),
                            MessageText = "Altera abhorreant referrentur eam ut, ne pro purto meis dolor.",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-07e2-2f47-b89d-0f362003ca83"),
                            AuthorId = new Guid("ec16e27a-47e2-4f47-b19d-2a362003ca83"),
                            MessageText = "Ad his pertinacia assueverit conclusionemque.",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ICS.Project.DAL.Entities.PostEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AuthorId");

                    b.Property<string>("MessageText");

                    b.Property<DateTime>("PublishDate");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            ID = new Guid("ec16e27a-07e2-0f47-b19d-0b362003ca83"),
                            AuthorId = new Guid("ec16e27a-47e2-4f47-b19d-0a362003ca83"),
                            MessageText = "Quo clita quaeque id, ei vel invenire persecuti.",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mediocrem"
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-17e2-4f47-b19d-0b362003ca83"),
                            AuthorId = new Guid("ec16e27a-47e2-4f47-b19d-1a362003ca83"),
                            MessageText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Novum"
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-27e2-4f47-b19d-0b362003ca83"),
                            AuthorId = new Guid("ec16e27a-47e2-4f47-b19d-2a362003ca83"),
                            MessageText = "Pro eu tation saperet, et sea brute similique theophrastus. Nec ex verear facilisi conceptam, novum postulant definitiones mei at.",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Euismod"
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-07e2-1f47-b19d-0b362003ca83"),
                            AuthorId = new Guid("ec16e27a-47e2-4f47-b19d-1a362003ca83"),
                            MessageText = "Partem scripta laoreet ei cum. Ea vel dico vocibus omittam, pro mollis tamquam efficiendi an.",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Splendide"
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-17e2-2f47-b19d-0b362003ca83"),
                            AuthorId = new Guid("ec16e27a-47e2-4f47-b19d-0a362003ca83"),
                            MessageText = "Mel at viris fuisset, vis diceret meliore ut.",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Imperdiet"
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-07e2-4f47-b19d-0b362003ca83"),
                            AuthorId = new Guid("ec16e27a-47e2-4f47-b19d-3a362003ca83"),
                            MessageText = "Nec iudico soluta vocent id, qui ferri perfecto te. Quo id tota dicam volumus.",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Putent"
                        });
                });

            modelBuilder.Entity("ICS.Project.DAL.Entities.TeamEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            ID = new Guid("ec16e27a-07e2-4f47-b19d-0a362003ca83"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Name = "The Lewd Turtles"
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-17e2-4f47-b19d-0a362003ca83"),
                            Description = "Pro eu tation saperet, et sea brute similique theophrastus. Nec ex verear facilisi conceptam, novum postulant definitiones mei at.",
                            Name = "Black Wariors"
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-27e2-4f47-b19d-0a362003ca83"),
                            Description = "Partem scripta laoreet ei cum. Ea vel dico vocibus omittam, pro mollis tamquam efficiendi an.",
                            Name = "The Six Eagles"
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-37e2-4f47-b19d-0a362003ca83"),
                            Description = "Mel at viris fuisset, vis diceret meliore ut.",
                            Name = "The Jagged Penguins"
                        });
                });

            modelBuilder.Entity("ICS.Project.DAL.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<int>("IterationCount");

                    b.Property<DateTime>("LastActivity");

                    b.Property<string>("Name");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("Salt");

                    b.Property<string>("Surname");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = new Guid("ec16e27a-47e2-4f47-b19d-0a362003ca83"),
                            Email = "student@fit.cz",
                            IterationCount = 10007,
                            LastActivity = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Student",
                            PasswordHash = new byte[] { 19, 36, 234, 204, 83, 41, 69, 76, 27, 40, 176, 157, 35, 181, 37, 35 },
                            Salt = new byte[] { 116, 214, 110, 237, 125, 7, 30, 5, 219, 149, 182, 93, 62, 91, 71, 69, 105, 152, 66, 44, 114, 122, 219, 28, 219, 147, 127, 133, 67, 116, 206, 143 },
                            Surname = "Roberts"
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-47e2-4f47-b19d-1a362003ca83"),
                            IterationCount = 0,
                            LastActivity = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Regan",
                            Surname = "Wiggins"
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-47e2-4f47-b19d-2a362003ca83"),
                            IterationCount = 0,
                            LastActivity = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kimberl",
                            Surname = "Cohen"
                        },
                        new
                        {
                            ID = new Guid("ec16e27a-47e2-4f47-b19d-3a362003ca83"),
                            IterationCount = 0,
                            LastActivity = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kelley",
                            Surname = "Watts"
                        });
                });

            modelBuilder.Entity("ICS.Project.DAL.Entities.UserInTeamEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("TeamId");

                    b.Property<Guid?>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("UserInTeam");

                    b.HasData(
                        new
                        {
                            ID = new Guid("709ece27-ac92-4d56-a8aa-2016fa63a6eb"),
                            TeamId = new Guid("ec16e27a-07e2-4f47-b19d-0a362003ca83"),
                            UserId = new Guid("ec16e27a-47e2-4f47-b19d-0a362003ca83")
                        },
                        new
                        {
                            ID = new Guid("719ece27-ac92-4d56-a8aa-2016fa63a6eb"),
                            TeamId = new Guid("ec16e27a-17e2-4f47-b19d-0a362003ca83"),
                            UserId = new Guid("ec16e27a-47e2-4f47-b19d-0a362003ca83")
                        },
                        new
                        {
                            ID = new Guid("729ece27-ac92-4d56-a8aa-2016fa63a6eb"),
                            TeamId = new Guid("ec16e27a-27e2-4f47-b19d-0a362003ca83"),
                            UserId = new Guid("ec16e27a-47e2-4f47-b19d-0a362003ca83")
                        },
                        new
                        {
                            ID = new Guid("739ece27-ac92-4d56-a8aa-2016fa63a6eb"),
                            TeamId = new Guid("ec16e27a-37e2-4f47-b19d-0a362003ca83"),
                            UserId = new Guid("ec16e27a-47e2-4f47-b19d-0a362003ca83")
                        },
                        new
                        {
                            ID = new Guid("749ece27-ac92-4d56-a8aa-2016fa63a6eb"),
                            TeamId = new Guid("ec16e27a-07e2-4f47-b19d-0a362003ca83"),
                            UserId = new Guid("ec16e27a-47e2-4f47-b19d-1a362003ca83")
                        },
                        new
                        {
                            ID = new Guid("759ece27-ac92-4d56-a8aa-2016fa63a6eb"),
                            TeamId = new Guid("ec16e27a-07e2-4f47-b19d-0a362003ca83"),
                            UserId = new Guid("ec16e27a-47e2-4f47-b19d-2a362003ca83")
                        },
                        new
                        {
                            ID = new Guid("769ece27-ac92-4d56-a8aa-2016fa63a6eb"),
                            TeamId = new Guid("ec16e27a-07e2-4f47-b19d-0a362003ca83"),
                            UserId = new Guid("ec16e27a-47e2-4f47-b19d-3a362003ca83")
                        },
                        new
                        {
                            ID = new Guid("779ece27-ac92-4d56-a8aa-2016fa63a6eb"),
                            TeamId = new Guid("ec16e27a-17e2-4f47-b19d-0a362003ca83"),
                            UserId = new Guid("ec16e27a-47e2-4f47-b19d-1a362003ca83")
                        },
                        new
                        {
                            ID = new Guid("789ece27-ac92-4d56-a8aa-2016fa63a6eb"),
                            TeamId = new Guid("ec16e27a-17e2-4f47-b19d-0a362003ca83"),
                            UserId = new Guid("ec16e27a-47e2-4f47-b19d-2a362003ca83")
                        },
                        new
                        {
                            ID = new Guid("799ece27-ac92-4d56-a8aa-2016fa63a6eb"),
                            TeamId = new Guid("ec16e27a-27e2-4f47-b19d-0a362003ca83"),
                            UserId = new Guid("ec16e27a-47e2-4f47-b19d-3a362003ca83")
                        });
                });

            modelBuilder.Entity("ICS.Project.DAL.Entities.CommentEntity", b =>
                {
                    b.HasOne("ICS.Project.DAL.Entities.UserEntity", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("ICS.Project.DAL.Entities.PostEntity", "Post")
                        .WithMany()
                        .HasForeignKey("PostId");
                });

            modelBuilder.Entity("ICS.Project.DAL.Entities.PostEntity", b =>
                {
                    b.HasOne("ICS.Project.DAL.Entities.UserEntity", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");
                });

            modelBuilder.Entity("ICS.Project.DAL.Entities.UserInTeamEntity", b =>
                {
                    b.HasOne("ICS.Project.DAL.Entities.TeamEntity", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.HasOne("ICS.Project.DAL.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
